Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [3]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [5]:
a_centered_transpose = np.transpose(a_centered)
a_centered_sp = np.inner(a_centered_transpose[0], a_centered_transpose[1])
a_centered_sp / (len(a) - 1)

2.0

Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

Подробнее узнать о ковариации можно здесь:

*Выборочная ковариация и выборочная дисперсия — Студопедия*

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [6]:
a_transpose = np.transpose(a)
np.cov(a_transpose)

array([[1. , 2. ],
       [2. , 4.3]])

Задание 5**

Создайте одномерный массив z случайных целых чисел из равномерного распределения от -50 до 50 включительно размерности 8. Найдите индексы положительных объектов.

In [7]:
z = np.random.randint(-50, 50+1, 8)
z

array([ 20,  -2,  31, -40, -42,  30,  20,  50])

In [8]:
np.where(z > 0)

(array([0, 2, 5, 6, 7]),)

Задание 6**

Создайте двумерный массив X случайных равномерно распределенных целых чисел от 0 до 255 включительно размерности 10 на 5. (Здесь снова считаем, что каждый столбец - это признак, а строка - наблюдение.)

Найдите среднее значение и стандартное отклонение по каждому признаку.

Вычислите массив X_standard, отняв от каждого признака среднее и поделив на стандартное отклонение.

Убедитесь, что теперь среднее в каждом признаке стало равное нулю, а стандартное отклонение равно единице.

Это называется стандартизация данных - важный процесс подготовки данных. Более подробно можно почитать здесь (https://wiki.loginom.ru/articles/data-standartization.html)

In [9]:
X = np.random.randint(0, 255+1, (10, 5))
X

array([[125, 221,  29, 146, 123],
       [166, 202,  13, 190,  94],
       [ 74, 192, 194,  37,  82],
       [ 45,  89, 101, 119, 121],
       [ 89,  47, 225, 212, 213],
       [197,  65,  43,  97,  83],
       [ 90, 249, 171, 250, 199],
       [230, 190,  75,  98,  32],
       [ 68, 121,  44,  76, 171],
       [216, 135, 198,  82, 168]])

In [10]:
mean_X = X.mean(axis=0)
mean_X

array([130. , 151.1, 109.3, 130.7, 128.6])

In [11]:
std_X = X.std(axis=0)
std_X

array([63.79028139, 65.96885629, 76.06714139, 64.09219921, 55.04398241])

In [12]:
X_standard = (X - mean_X) / std_X
X_standard

array([[-0.07838185,  1.0595909 , -1.05564635,  0.2387186 , -0.10173682],
       [ 0.56434929,  0.77157621, -1.26598684,  0.9252296 , -0.62858824],
       [-0.87787667,  0.61998953,  1.11348998, -1.46195639, -0.84659572],
       [-1.33249138, -0.94135329, -0.10911413, -0.18254952, -0.13807141],
       [-0.64273114, -1.57801735,  1.52102469,  1.2684851 ,  1.53331929],
       [ 1.05031673, -1.30516133, -0.87159842, -0.52580502, -0.82842843],
       [-0.62705477,  1.48403361,  0.81112553,  1.86138097,  1.27897723],
       [ 1.56763692,  0.58967219, -0.45091743, -0.5102025 , -1.75496023],
       [-0.97193489, -0.45627591, -0.85845214, -0.853458  ,  0.7702931 ],
       [ 1.34816775, -0.24405456,  1.16607511, -0.75984286,  0.71579123]])

In [13]:
mean_X_standard = X_standard.mean(axis=0)
mean_X_standard

array([0.00000000e+00, 8.32667268e-17, 2.22044605e-17, 1.77635684e-16,
       1.22124533e-16])

In [14]:
std_X_standard = X_standard.std(axis=0)
std_X_standard

array([1., 1., 1., 1., 1.])

Задание 7**

Создайте два одномерных массива размерности 512 с любыми значениями. Будем считать, что каждый массив - это наблюдение с 512 признаками. 

Найдите разницу между двумя массивами. Далее возведите разницу в квадрат, просуммируйте все элементы нового массива и возьмите корень квадратный.

Это получилась L2-норма (Евклидова метрика) — функция расстояния, благодаря которой можно считать насколько далеки точки друг от друга, насколько они похожи друг на друга. Более подробно здесь (https://wiki.loginom.ru/articles/euclid-distance.html)

Посчитайте L2 норму для этих двух массивов с помощью numpy.linalg.

In [15]:
x_512 = np.random.randint(0, 999+1, 512)
y_512 = np.random.randint(0, 999+1, 512)

In [16]:
difference_x_y = x_512 - y_512
square_dif = difference_x_y ** 2
my_sum = sum(square_dif)
my_sqrt = np.sqrt(my_sum)
# difference_x_y
# square_dif
# my_sum
my_sqrt

9321.914181111088

In [17]:
np.linalg.norm(x_512)

13008.645317633962

In [18]:
np.linalg.norm(y_512)

12588.027526185348

Задание 8**

Используйте ранее созданный массив X.

Найдите минимальное значение и максимальное по каждому признаку.

Вычислите массив X_norm, отняв от каждого признака минимальное и поделив на разницу максимального и минимального.

Убедитесь, что теперь минимальное значение стало равно 0, а максимальное - 1.

Это называется нормализация данных - еще один из важных процессов подготовки данных. Более подробно здесь (https://wiki.loginom.ru/articles/data-normalization.html)

In [19]:
min_X = X.min(axis=0)
min_X

array([45, 47, 13, 37, 32])

In [20]:
max_X = X.max(axis=0)
max_X

array([230, 249, 225, 250, 213])

In [21]:
X_norm = (X - min_X) / (max_X - min_X)
X_norm

array([[0.43243243, 0.86138614, 0.0754717 , 0.51173709, 0.50276243],
       [0.65405405, 0.76732673, 0.        , 0.71830986, 0.34254144],
       [0.15675676, 0.71782178, 0.85377358, 0.        , 0.27624309],
       [0.        , 0.20792079, 0.41509434, 0.38497653, 0.49171271],
       [0.23783784, 0.        , 1.        , 0.82159624, 1.        ],
       [0.82162162, 0.08910891, 0.14150943, 0.28169014, 0.28176796],
       [0.24324324, 1.        , 0.74528302, 1.        , 0.92265193],
       [1.        , 0.70792079, 0.29245283, 0.28638498, 0.        ],
       [0.12432432, 0.36633663, 0.14622642, 0.18309859, 0.7679558 ],
       [0.92432432, 0.43564356, 0.87264151, 0.21126761, 0.75138122]])

In [22]:
X_norm.min(axis=0)

array([0., 0., 0., 0., 0.])

In [23]:
X_norm.max(axis=0)

array([1., 1., 1., 1., 1.])