**Тема “Вычисления с помощью Numpy”**

Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [53]:
import numpy as np

In [54]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [55]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [56]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [57]:
a_centered_transpose = np.transpose(a_centered)
a_centered_sp = np.inner(a_centered_transpose[0], a_centered_transpose[1])
a_centered_sp / (len(a) - 1)

2.0

Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

Подробнее узнать о ковариации можно здесь:

*Выборочная ковариация и выборочная дисперсия — Студопедия*

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [58]:
a_transpose = np.transpose(a)
np.cov(a_transpose)

array([[1. , 2. ],
       [2. , 4.3]])

Задание 5**

Создайте одномерный массив z случайных целых чисел из равномерного распределения от -50 до 50 включительно размерности 8. Найдите индексы положительных объектов.

In [59]:
z = np.random.randint(-50, 50+1, 8)
z

array([  0, -34,   4, -38, -16,  47,   8,  47])

In [60]:
np.where(z > 0)

(array([2, 5, 6, 7]),)

Задание 6**

Создайте двумерный массив X случайных равномерно распределенных целых чисел от 0 до 255 включительно размерности 10 на 5. (Здесь снова считаем, что каждый столбец - это признак, а строка - наблюдение.)

Найдите среднее значение и стандартное отклонение по каждому признаку.

Вычислите массив X_standard, отняв от каждого признака среднее и поделив на стандартное отклонение.

Убедитесь, что теперь среднее в каждом признаке стало равное нулю, а стандартное отклонение равно единице.

Это называется стандартизация данных - важный процесс подготовки данных. Более подробно можно почитать здесь (https://wiki.loginom.ru/articles/data-standartization.html)

In [61]:
X = np.random.randint(0, 255+1, (10, 5))
X

array([[157,  87, 237,  35, 159],
       [ 92,   0,  66, 146,  69],
       [ 59, 105,  57, 240, 121],
       [208, 232,  13,   9, 255],
       [167, 243,  39,  12, 104],
       [247,  17, 133,  39, 232],
       [246,  44, 202, 255,  28],
       [ 97,   7, 174,  11,  59],
       [184,  91, 220,  61,   3],
       [137, 155,  22,  90, 114]])

In [62]:
mean_X = X.mean(axis=0)
mean_X

array([159.4,  98.1, 116.3,  89.8, 114.4])

In [63]:
std_X = X.std(axis=0)
std_X

array([61.01016309, 83.55291736, 82.377242  , 88.43845318, 77.93869386])

In [64]:
X_standard = (X - mean_X) / std_X
X_standard

array([[-0.03933771, -0.13284994,  1.4652105 , -0.61963996,  0.57224464],
       [-1.10473398, -1.17410622, -0.61060554,  0.63547018, -0.58250912],
       [-1.64562746,  0.08258239, -0.71985901,  1.69835625,  0.08468194],
       [ 0.79658859,  1.6025772 , -1.25398711, -0.91362973,  1.80398199],
       [ 0.12456941,  1.73423029, -0.93836596, -0.87970783, -0.13343821],
       [ 1.43582635, -0.97064235,  0.20272589, -0.57441077,  1.50887825],
       [ 1.41943564, -0.64749385,  1.04033587,  1.86796573, -1.10856361],
       [-1.02278042, -1.09032698,  0.70043617, -0.89101513, -0.71081509],
       [ 0.40321151, -0.08497609,  1.25884282, -0.3256502 , -1.42932855],
       [-0.36715194,  0.68100554, -1.14473364,  0.00226146, -0.00513224]])

In [65]:
mean_X_standard = X_standard.mean(axis=0)
mean_X_standard

array([-6.66133815e-17,  8.88178420e-17, -2.22044605e-17, -1.14925430e-17,
       -6.34908792e-17])

In [66]:
std_X_standard = X_standard.std(axis=0)
std_X_standard

array([1., 1., 1., 1., 1.])

Задание 7**

Создайте два одномерных массива размерности 512 с любыми значениями. Будем считать, что каждый массив - это наблюдение с 512 признаками. 

Найдите разницу между двумя массивами. Далее возведите разницу в квадрат, просуммируйте все элементы нового массива и возьмите корень квадратный.

Это получилась L2-норма (Евклидова метрика) — функция расстояния, благодаря которой можно считать насколько далеки точки друг от друга, насколько они похожи друг на друга. Более подробно здесь (https://wiki.loginom.ru/articles/euclid-distance.html)

Посчитайте L2 норму для этих двух массивов с помощью numpy.linalg.

In [67]:
x_512 = np.random.randint(0, 999+1, 512)
y_512 = np.random.randint(0, 999+1, 512)

In [68]:
difference_x_y = x_512 - y_512
square_dif = difference_x_y ** 2
my_sum = sum(square_dif)
my_sqrt = np.sqrt(my_sum)
# difference_x_y
# square_dif
# my_sum
my_sqrt

9423.705905852537

In [69]:
np.linalg.norm(x_512)

13211.980623661238

In [70]:
np.linalg.norm(y_512)

13453.26878494591

Задание 8**

Используйте ранее созданный массив X.

Найдите минимальное значение и максимальное по каждому признаку.

Вычислите массив X_norm, отняв от каждого признака минимальное и поделив на разницу максимального и минимального.

Убедитесь, что теперь минимальное значение стало равно 0, а максимальное - 1.

Это называется нормализация данных - еще один из важных процессов подготовки данных. Более подробно здесь (https://wiki.loginom.ru/articles/data-normalization.html)

In [71]:
min_X = X.min(axis=0)
min_X

array([59,  0, 13,  9,  3])

In [72]:
max_X = X.max(axis=0)
max_X

array([247, 243, 237, 255, 255])

In [73]:
X_norm = (X - min_X) / (max_X - min_X)
X_norm

array([[0.5212766 , 0.35802469, 1.        , 0.10569106, 0.61904762],
       [0.17553191, 0.        , 0.23660714, 0.55691057, 0.26190476],
       [0.        , 0.43209877, 0.19642857, 0.93902439, 0.46825397],
       [0.79255319, 0.95473251, 0.        , 0.        , 1.        ],
       [0.57446809, 1.        , 0.11607143, 0.01219512, 0.40079365],
       [1.        , 0.06995885, 0.53571429, 0.12195122, 0.90873016],
       [0.99468085, 0.18106996, 0.84375   , 1.        , 0.09920635],
       [0.20212766, 0.02880658, 0.71875   , 0.00813008, 0.22222222],
       [0.66489362, 0.3744856 , 0.92410714, 0.21138211, 0.        ],
       [0.41489362, 0.63786008, 0.04017857, 0.32926829, 0.44047619]])

In [74]:
X_norm.min(axis=0)

array([0., 0., 0., 0., 0.])

In [75]:
X_norm.max(axis=0)

array([1., 1., 1., 1., 1.])

**Тема “Работа с данными в Pandas”**

Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].

In [76]:
import pandas as pd

In [77]:
authors = pd.DataFrame(
    {
        "author_id": [1, 2, 3],
        "author_name": ['Тургенев', 'Чехов', 'Островский'],
    }
)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [78]:
book = pd.DataFrame(
    {
        "author_id": [1, 1, 1, 2, 2, 3, 3],
        " book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
        "price": [450, 300, 350, 500, 450, 370, 290],
    }
)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.

In [79]:
authors_price = pd.merge(authors, book, on = "author_id", how = "outer")
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [80]:
top5 = authors_price.sort_values(by="price", ascending=False).head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [81]:
authors_price_min = authors_price.groupby("author_name").agg({"price": "min"}).rename(columns={"price": "min_price"})
authors_price_max = authors_price.groupby("author_name").agg({"price": "max"}).rename(columns={"price": "max_price"})
authors_price_mean = authors_price.groupby("author_name").agg({"price": "mean"}).rename(columns={"price": "mean_price"})

In [82]:
min_max = pd.merge(authors_price_min, authors_price_max, on = "author_name", how = "outer")
authors_stat = pd.merge(min_max, authors_price_mean, on = "author_name", how = "outer")
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

Задание 5**

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.

Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.

In [83]:
authors_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [84]:
?pd.pivot_table

In [85]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [86]:
book_info.to_pickle('/content/drive/MyDrive/Colab Notebooks/book_info.pkl')

In [87]:
book_info2 = pd.read_pickle('/content/drive/MyDrive/Colab Notebooks/book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

Задание 6**

В этом задании будем работать с датасетом, в котором представлены данные по сериалам и фильмам на Netflix (Netflix Movies and TV Shows).

Ознакомьтесь с описанием данных и скачайте датасет netflix_titles.csv с сайта Kaggle.com https://www.kaggle.com/shivamb/netflix-shows

Считайте датасет. Посмотрите, сколько наблюдений и сколько признаков есть в этом наборе данных.

Посчитайте, как много сериалов и фильмов представлено в этом датасете.

Посчитайте, как много пропущенных значений (NaN) есть в признаках director и country.

Посчитайте, сколько фильмов выпустили раньше 2003 года.

Посчитайте, какая страна чаще всего выпускает фильмы на Netflix.


**TV Shows and Movies listed on Netflix**

This dataset consists of tv shows and movies available on Netflix as of 2019. The dataset is collected from Flixable which is a third-party Netflix search engine.

In 2018, they released an interesting report which shows that the number of TV shows on Netflix has nearly tripled since 2010. The streaming service’s number of movies has decreased by more than 2,000 titles since 2010, while its number of TV shows has nearly tripled. It will be interesting to explore what all other insights can be obtained from the same dataset.

Integrating this dataset with other external datasets such as IMDB ratings, rotten tomatoes can also provide many interesting findings.
Inspiration

Some of the interesting questions (tasks) which can be performed on this dataset -

    Understanding what content is available in different countries
    Identifying similar content by matching text-based features
    Network analysis of Actors / Directors and find interesting insights
    Is Netflix has increasingly focusing on TV rather than movies in recent years.


In [88]:
nt = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/netflix_titles.csv')
nt.head()

show_id  ...                                        description
0      s1  ...  In a future where the elite inhabit an island ...
1      s2  ...  After a devastating earthquake hits Mexico Cit...
2      s3  ...  When an army recruit is found dead, his fellow...
3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

In [89]:
tv_show = nt[nt["type"] == "TV Show"]
tv_show["type"].count()

2410

In [90]:
movie = nt[nt["type"] == "Movie"]
movie["type"].count()

5377

In [91]:
nt["director"].isnull().sum()

2389

In [92]:
nt["country"].isnull().sum()

507

In [93]:
movie_before = movie[movie["release_year"] < 2003]
movie_before["type"].count()

503

In [94]:
nt["country"].value_counts()

United States                                    2555
India                                             923
United Kingdom                                    397
Japan                                             226
South Korea                                       183
                                                 ... 
United States, Bermuda, Ecuador                     1
Spain, France, Canada                               1
Spain, Canada, United States                        1
United Kingdom, Spain, United States, Germany       1
United States, China, Colombia                      1
Name: country, Length: 681, dtype: int64

Задание 7**

В этом датасете есть признак date_added (дата добавления сериала/фильма на платформу), на основе этого признака создайте три новых: year_added - год добавления, month_added - месяц добавления и day_added - день добавления.

In [95]:
nt["year_added"] = nt["date_added"]

idx = 0
for i in nt["date_added"]:
  try:
    nt["year_added"].iloc[idx] = nt["date_added"].iloc[idx].split(' ')[2]
    idx += 1
  except AttributeError:
    continue

nt["year_added"]

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


0                     2020
1                     2016
2                     2018
3                     2017
4                     2020
               ...        
7782      October 19, 2020
7783         March 2, 2019
7784    September 25, 2020
7785      October 31, 2020
7786         March 1, 2020
Name: year_added, Length: 7787, dtype: object

In [96]:
nt["month_added"] = nt["date_added"]

idx = 0
for i in nt["date_added"]:
  try:
    nt["month_added"].iloc[idx] = nt["date_added"].iloc[idx].split(' ')[0]
    idx += 1
  except AttributeError:
    continue

nt["month_added"]

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


0                   August
1                 December
2                 December
3                 November
4                  January
               ...        
7782      October 19, 2020
7783         March 2, 2019
7784    September 25, 2020
7785      October 31, 2020
7786         March 1, 2020
Name: month_added, Length: 7787, dtype: object

In [97]:
nt["day_added"] = nt["date_added"]

idx = 0
for i in nt["date_added"]:
  try:
    nt["day_added"].iloc[idx] = nt["date_added"].iloc[idx].split(' ')[1]
    idx += 1
  except AttributeError:
    continue

nt["day_added"]

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


0                      14,
1                      23,
2                      20,
3                      16,
4                       1,
               ...        
7782      October 19, 2020
7783         March 2, 2019
7784    September 25, 2020
7785      October 31, 2020
7786         March 1, 2020
Name: day_added, Length: 7787, dtype: object

Задание 8**

Выберите только наблюдения, где страна 'United States', 'India' или 'United Kingdom'

Для каждой страны посчитайте общее количество фильмов и сериалов по месяцам выпуска. Столбцы нового сводного датафрейма должны называться, как месяца в признаке month_added, а индексов будет два: страна и тип.

In [98]:
result_nt = nt[(nt["country"] == "United States") | (nt["country"] == "India") | (nt["country"] == "United Kingdom")]
result_nt

show_id   type  ...       month_added         day_added
3         s4  Movie  ...          November               16,
4         s5  Movie  ...           January                1,
7         s8  Movie  ...          November                1,
8         s9  Movie  ...             April                1,
9        s10  Movie  ...          December               15,
...      ...    ...  ...               ...               ...
7776   s7777  Movie  ...  November 1, 2018  November 1, 2018
7778   s7779  Movie  ...  November 1, 2019  November 1, 2019
7780   s7781  Movie  ...      July 1, 2018      July 1, 2018
7781   s7782  Movie  ...  January 11, 2020  January 11, 2020
7783   s7784  Movie  ...     March 2, 2019     March 2, 2019

[3875 rows x 15 columns]

In [99]:
pd.pivot_table(
    data=result_nt,
    values="type",
    index="country",
    columns="month_added",
    aggfunc="count"
)

month_added      April 4, 2017  ...  September 9, 2020
country                         ...                   
India                      NaN  ...                1.0
United Kingdom             1.0  ...                NaN
United States              NaN  ...                2.0

[3 rows x 1187 columns]