Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [ ]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [ ]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [ ]:
a_centered_transpose = np.transpose(a_centered)
a_centered_sp = np.inner(a_centered_transpose[0], a_centered_transpose[1])
a_centered_sp / (len(a) - 1)

2.0

Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

Подробнее узнать о ковариации можно здесь:

*Выборочная ковариация и выборочная дисперсия — Студопедия*

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [ ]:
a_transpose = np.transpose(a)
np.cov(a_transpose)

array([[1. , 2. ],
       [2. , 4.3]])

Задание 5**

Создайте одномерный массив z случайных целых чисел из равномерного распределения от -50 до 50 включительно размерности 8. Найдите индексы положительных объектов.

In [ ]:
z = np.random.randint(-50, 50+1, 8)
z

array([-23, -37,  14,  37,   7, -16,  17, -33])

In [ ]:
np.where(z > 0)

(array([2, 3, 4, 6]),)

Задание 6**

Создайте двумерный массив X случайных равномерно распределенных целых чисел от 0 до 255 включительно размерности 10 на 5. (Здесь снова считаем, что каждый столбец - это признак, а строка - наблюдение.)

Найдите среднее значение и стандартное отклонение по каждому признаку.

Вычислите массив X_standard, отняв от каждого признака среднее и поделив на стандартное отклонение.

Убедитесь, что теперь среднее в каждом признаке стало равное нулю, а стандартное отклонение равно единице.

Это называется стандартизация данных - важный процесс подготовки данных. Более подробно можно почитать здесь (https://wiki.loginom.ru/articles/data-standartization.html)

In [ ]:
X = np.random.randint(0, 255+1, (10, 5))
X

array([[216,   5, 184,  52, 253],
       [196, 195,  46, 237,  68],
       [ 99, 144, 228,   1, 203],
       [143,  17, 234, 223, 140],
       [149, 223,  51, 210,   4],
       [ 29, 197, 148, 250,  69],
       [  4,  25,  49, 204, 164],
       [251,  61, 233,  43, 125],
       [153, 195,  39, 184, 222],
       [213, 186,  14,  84, 246]])

In [ ]:
mean_X = X.mean(axis=0)
mean_X

array([131.7,  98.2, 172.7, 149.8, 115.2])

In [ ]:
std_X = X.std(axis=0)
std_X

array([87.17115349, 78.08815531, 62.40520812, 67.12048868, 46.81196428])

In [ ]:
X_standard = (X - mean_X) / std_X
X_standard

array([[ 1.35710032,  0.70177096,  0.67782804,  0.0923712 , -0.00427241],
       [ 1.09325157, -0.84775981,  0.74192526, -0.69725356, -1.30735809],
       [ 1.18502504,  1.67502996, -0.8284565 , -0.6674564 , -1.32872015],
       [-0.4439542 , -0.60444506,  0.08492881,  0.241357  ,  0.52977909],
       [-0.22599219,  0.59932265, -1.45340433,  0.53932861,  2.21738185],
       [-1.23550046, -0.8093417 ,  0.66180374, -0.5184706 , -0.77330658],
       [-1.16667035, -0.46357863,  1.22265436, -2.14241587,  0.7433997 ],
       [ 0.41642216, -0.75811754, -0.36375169,  0.49463287,  0.31615849],
       [ 0.45083721, -1.1038806 ,  1.01433842,  1.52263492, -0.19653095],
       [-1.4305191 ,  1.61099977, -1.7578661 ,  1.13527183, -0.19653095]])

In [ ]:
mean_X_standard = X_standard.mean(axis=0)
mean_X_standard

array([ 8.88178420e-17, -2.22044605e-17,  1.77635684e-16, -1.77635684e-16,
       -3.33066907e-17])

In [ ]:
std_X_standard = X_standard.std(axis=0)
std_X_standard

array([1., 1., 1., 1., 1.])

Задание 7**

Создайте два одномерных массива размерности 512 с любыми значениями. Будем считать, что каждый массив - это наблюдение с 512 признаками. 

Найдите разницу между двумя массивами. Далее возведите разницу в квадрат, просуммируйте все элементы нового массива и возьмите корень квадратный.

Это получилась L2-норма (Евклидова метрика) — функция расстояния, благодаря которой можно считать насколько далеки точки друг от друга, насколько они похожи друг на друга. Более подробно здесь (https://wiki.loginom.ru/articles/euclid-distance.html)

Посчитайте L2 норму для этих двух массивов с помощью numpy.linalg.